# This is a basic workflow to help you get started with Actions

name: Java CI with Gradle
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build  
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      env:
        # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
           -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
           -Dsonar.projectKey=SMA_Test_Project
           -Dsonar.projectName=SMA_Test_Project
           -Dsonar.projectVersion=v0.0.1
           -Dsonar.sources=src/main
           -Dsonar.java.binaries=build/classes/java/main
           -Dsonar.java.test.binaries=build/classes/java/test
           -Dsonar.jacoco.reportPaths=build/jacoco/jacoco.exec
           -Dsonar.java.libraries=build/libs/*.jar
